version: 2

models:

  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: dim_product
    columns:
      - name: product_id
        tests:
          - not_null

  - name: fact_transactions
    columns:
      - name: InvoiceNo
        tests:
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null

  - name: fact_returns
    columns:
      - name: InvoiceNo
        tests:
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null

  - name: mart_rfm
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique